<% password = ENV['DATABASE_PASSWORD'] %>
default:
  adapter: postgresql
  encoding: unicode
  pool: 8
  username: k0kubun
  password: <%= password %>
  host: 127.0.0.1

# ... rest of your configurations ...

# ... rest of your configurations ...


development:
  adapter: postgresql
  encoding: unicode
  pool: 8
  username: k0kubun
  password: <%= password %>
  host: 127.0.0.1
  database: gitstar_ranking

test:
  adapter: postgresql
  encoding: unicode
  pool: 8
  username: k0kubun
  password: <%= password %>
  host: 127.0.0.1
  database: gitstar_ranking_test

production:
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV.fetch('POOL_SIZE', '4') %>
  database: <%= ENV.fetch('DATABASE_NAME', 'gitstar_ranking') %>
